#!/bin/sh

# This script is not meant to add the RIGHT permissions, per-se,
# it's meant to add some sane default so you can use the exmaple
# config to test out rubix

dir=$1

if [ -z $dir ] ; then
	echo "Usage: $0 <configdir>"
	exit 1;
fi

find $dir -path '*overlay*' -type d -exec chmod 755 '{}' \;
find $dir -path '*overlay*' -type f -exec chmod 644 '{}' \;
