#!/bin/bash

apt-get install -y libnet-dns-perl libtemplate-perl libyaml-syck-perl libtext-diff-perl libnetaddr-ip-perl libwww-perl libdigest-md5-file-perl libfile-temp-perl libfile-finder-perl liblchown-perl libconfig-simple-perl libxml-simple-perl
